sudo: true

language: node_js
node_js: 8

cache:
  directories:
    - "node_modules/"

install: npm install eslint
script: eslint --no-eslintrc src/content.js

notifications:
  email:
    on_success: change
    on_failure: always
